spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/gamified_learning}
      database: gamified_learning
  application:
    name: gamified-learning-tracker

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.gamifiedlearning.tracker: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true